# Generated by Django 2.0.1 on 2018-03-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=6, verbose_name='シンボル')),
                ('period', models.IntegerField(verbose_name='時間軸')),
                ('high', models.DecimalField(decimal_places=5, max_digits=6, verbose_name='高値')),
                ('low', models.DecimalField(decimal_places=5, max_digits=6, verbose_name='安値')),
                ('open', models.DecimalField(decimal_places=5, max_digits=6, verbose_name='始値')),
                ('close', models.DecimalField(decimal_places=5, max_digits=6, verbose_name='終値')),
                ('time', models.DateTimeField(verbose_name='日時')),
            ],
        ),
    ]
