# Generated by Django 2.0.3 on 2018-03-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='BasicData',
        ),
    ]
